syntax = "proto3";

option java_package = "ru.vicria.event.service.api";
option java_outer_classname = "EventServiceApi";
option java_multiple_files = true;

service EventService {
  rpc ListenEvent (ListenEventRequest) returns (stream Event);
  rpc AnalyzeEvents (stream AnalyticsEvent) returns (EventAnalysisResult);
}

message AnalyticsEvent {
    RequestId request_id = 1;
    Event event = 2;
}

message EventAnalysisResult {
    RequestId request_id = 1;
    int64 total_events = 2;
    int64 latest_notification_time = 3;
    int64 total_message_chars = 4;
}

message RequestId {
  string trace_id = 1;
  string client_id = 2;
}

message ListenEventRequest {
  RequestId request_id = 1;
  int64 starting_from = 2;
}

message Event {
  int64 notification_time = 1;
  string message = 2;
}